eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8090
spring:
  application:
    name: students
  r2dbc:
      url: r2dbc:mysql://localhost:3306/student
      username:
      password:
  flyway:
    url: jdbc:mysql://localhost:3306/student
    username:
    password:
#  r2dbc:
#      url: r2dbc:sqlserver://localhost:1433;database=dukaletu
#      username: sa
#      password: smartkip
#      pool:
#        initial-size: 10
#  datasource:
#    url: r2dbc:sqlserver://localhost:1433;databaseName=dukaletu;encrypt=false;
#    username: sa
#    password: smartkip
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
#  encrypt=false